### ISSUE TITLE
Syntax error on line 287 ??

### ISSUE THREAD

**Issue by dhyannirav** [quentinsf/IMAPdedup#50]
When I try to run, I get

```
  File "./imapdedup.py", line 287
    resp: List[Tuple[int, bytes]] = []
        ^
SyntaxError: invalid syntax
```

I know nothing about python, I'm lost to correct the problem...

**Comment by quentinsf** [comment]
Hi Dhyan - 

I'm guessing you're using an older version of Python?
You need to have at least Python 3.5, and 3.6 or later is best.

I'll leave this issue open until I get round to updating the documentation to make that clear!

All the best,

Quentin

**Comment by dhyannirav** [comment]
I tried with Python 3.5.3 on Debian and Python 3.8 on Windows... another idea ?

Christophe Steiger
m +41 76 822 1807

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinsf** [comment]
Hi Christophe - 

Sorry, I never got back to you on this, but I'm afraid I don't have any ideas.  It's not affecting the large number of other people using IMAPdedup, so I think it must be an issue with your system somewhere.  Python 3.8 certainly shouldn't have any problem, but Windows might...   

It could be the encoding of the text file?   It's been a couple of decades now since I used Windows, so I don't know how well Python copes with variations in Windows line-endings etc.

Anyway, I'm closing this but do come back if you still want to try it and have problems!

All the best,

Quentin
