### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JKDos** [quentinsf/IMAPdedup#56]
After processing 26200 out of 42171 emails

```
Traceback (most recent call last):
  File "imapdedup.py", line 536, in <module>
    main(sys.argv[1:])
  File "imapdedup.py", line 532, in main
    process(options, mboxes)
  File "imapdedup.py", line 440, in process
    for mnum, hinfo in get_msg_headers(server, msgnums[i: i + chunkSize]):
  File "imapdedup.py", line 315, in get_msg_headers
    mnum = int(msg_ids[ci])
IndexError: list index out of range
```

**Comment by quentinsf** [comment]
Mmm.  Haven't seen that one before.   Is it an Exchange server, by any chance?

**Comment by JKDos** [comment]
> Mmm. Haven't seen that one before. Is it an Exchange server, by any chance?

No. Just standard email. What's strange is I've run this against my own mailbox at least 5 times now and haven't had a problem. This error happened when I was running it against another user's mailbox to help clean up their duplicates. Our emails are hosted on the same server/domain. My inbox has a total of fewer than 21,000 emails. So I don't know if the size of the inbox is the culprit or if it's just a fluke

**Comment by quentinsf** [comment]
Some mail servers do just timeout on very large requests -- Exchange is a particular culprit, which is why I asked --  and there isn't anything in IMAPdedup that copes with this at present.

One workaround might be to move half of the messages into another mailbox, and try de-duping each half, then moving them back again?  If you do the split, say, by date range, it'll probably be close to 100% effective since duplicates are likely to be in the same half.

**Comment by melefabrizio** [comment]
I "solved" it by looping the script via bash until the exit code is not an error, interestingly in my case the error comes up later and later on in the process until it manages to process the whole mailbox
